name: Basic workflow

on:
  workflow_dispatch:
  push:
    branches: [main, releases/**]
#    tags: [v2, v1.*]
#  pull_request:
#    branches: [main, releases/**]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production-env
    env:
      DOCKER_REGISTRY: c8n.io
      DOCKER_IMAGE: alejandrosilva/express-docker

    steps:
      - uses: actions/checkout@v4

      - name: Creating envs
        run: |
          echo "IMAGE_TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_URI=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}" >> $GITHUB_ENV

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE_URI }}:${{env.IMAGE_TAG}},${{ env.DOCKER_IMAGE_URI}}:latest

      - name: sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'express-docker'
          stack-definition: 'stack-definition.yml'
          template-variables: '{"username": "MrCool", "IMAGE_TAG": "v1.1"}'
          #image: ${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }}